force-app/main/default/objects/PricePlan__c/PricePlan__c.object-meta.xml
<CustomObject>
    <label>Price Plan</label>
    <nameField>
        <label>Price Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reading__c/Reading__c.object-meta.xml
<CustomObject>
    <label>Reading</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reading No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reading__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Readings</relationshipLabel>
    <relationshipName>Readings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reading__c/fields/ReadingTime__c.field-meta.xml
<CustomField>
    <fullName>ReadingTime__c</fullName>
    <label>Reading Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reading__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UsageStub.cls
public without sharing class UsageStub {
    @testVisible
    private static Decimal average(Id clientId){
        AggregateResult[] results = [select 
                                        AVG(Value__c) aver 
                                        from Reading__c 
                                        where Client__c = :clientId];
        return (Decimal)(results[0].get('aver'));
    }

    @testVisible
    private static Integer timeElapsedInHours(Id clientId){
        Reading__c firstReading = [select Id, ReadingTime__c from Reading__c order by ReadingTime__c limit 1];
        Reading__c lastReading = [select Id, ReadingTime__c from Reading__c order by ReadingTime__c desc limit 1];
        Long firstReadingTime = firstReading.ReadingTime__c.getTime();
        Long lastReadingTime = lastReading.ReadingTime__c.getTime();
        return ((lastReadingTime - firstReadingTime) / 1000 / 3600).intValue();
    }

    @testVisible
    private static Decimal usage(Id clientId) {
        return average(clientId) / timeElapsedInHours(clientId);
    }

    @testVisible
    private static PlanCost getPlanCost(PricePlan__c plan, Id clientId) {
        Decimal cost = usage(clientId) * plan.Rate__c;
        return new PlanCost(plan, cost);
    }

    public static List<PlanCost> getUsageForAllPricePlans(Id clientId) {
        List<PlanCost> plans = new List<PlanCost>();
        for (PricePlan__c plan : [select Id, Name, Rate__c from PricePlan__c]) {
            plans.add(getPlanCost(plan, clientId));
        }
        return plans;
    }
}