force-app/main/default/objects/Contact/fields/MeterId__c.field-meta.xml
<CustomField>
    <fullName>MeterId__c</fullName>
    <externalId>true</externalId>
    <label>Meter Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/PricePlan__c.field-meta.xml
<CustomField>
    <fullName>PricePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Plan</label>
    <referenceTo>PricePlan__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PricePlan__c/PricePlan__c.object-meta.xml
<CustomObject>
    <label>Price Plan</label>
    <nameField>
        <label>Price Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PricePlan__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Plans</relationshipLabel>
    <relationshipName>Price_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reading__c/Reading__c.object-meta.xml
<CustomObject>
    <label>Reading</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reading No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ReadingsStubTest.cls
@isTest
public with sharing class ReadingsStubTest {
    @testSetup
    public static void initData(){
        List<Account> suppliers = new List<Account>();
        suppliers.add(new Account(Name = 'The Green Eco'));
        suppliers.add(new Account(Name = 'Power for Everyone'));
        suppliers.add(new Account(Name = 'Dr Evil\'s Dark Energy'));
        insert suppliers;
        List<PricePlan__c> supplierPlans = new List<PricePlan__c>();
        supplierPlans.add(new PricePlan__c(Supplier__c = suppliers[0].Id, Rate__c = 1));
        supplierPlans.add(new PricePlan__c(Supplier__c = suppliers[1].Id, Rate__c = 2));
        supplierPlans.add(new PricePlan__c(Supplier__c = suppliers[2].Id, Rate__c = 10));
        insert supplierPlans;

        Contact client = new Contact(LastName = 'Harry', MeterId__c = 'smart-meter-9527');
        insert client;
    }

    // should generate readings for a client.
    @isTest
    public static void testGenerateReadings(){
        Contact client = [select Id from Contact limit 1];
        ReadingsStub.initReadings(client.Id);
        System.assert([select count() from Reading__c] > 0, 'Incorrect readings quantity.');
    }

    // should not generate readings without a client Id.
    @isTest
    public static void testGenerateReadingsWithoutClientId(){
        ReadingsStub.initReadings(null);
        System.assert([select count() from Reading__c] == 0, 'Incorrect readings quantity.');
    }
}