force-app/main/default/objects/Reading__c/Reading__c.object-meta.xml
<CustomObject>
    <label>Reading</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reading No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reading__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Readings</relationshipLabel>
    <relationshipName>Readings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PlansStub.cls
public without sharing class PlansStub {
    @AuraEnabled(cacheable=true)
    public static List<PlanCost> recommend(Id clientId, Integer limits) {
        // To solve: List has no rows for assignment to SObject in UsageStub.timeElapsedInHours
        List<PlanCost> results = new List<PlanCost>();
        
        if([SELECT COUNT() FROM Reading__c WHERE Client__c = :clientId] > 0) {
            List<PlanCost> allPlans = UsageStub.getUsageForAllPricePlans(clientId);
            allPlans.sort();
            for (Integer i = 0; i < Math.min(limits, allPlans.size()); i++) 
                results.add(allPlans[i]);
        }

        System.debug('results: ' + results);
        return results;
    }

    public static List<PlanCost> compare(Id clientId) {
        return UsageStub.getUsageForAllPricePlans(clientId);
    }
}